name: Decoys
version: '1.0'
main: me.thelpro.decoys.Decoys
api-version: '1.20'
commands:
  decoys:
    description: Main command for the Decoys plugin
permissions:
  decoys.admin:
    description: Reload the plugin and spawn decoys